### PR TITLE
Pandoc quirk

### PR DESCRIPTION
**Pull request by craigmayhew**
Hi David,

This \\# appearing at the beginning of some example code confused me. This PR fixes it.

### CODE REVIEW

**Comment by craigmayhew** [comment]
I was incorrect, it doesn't fix it :/ https://5d3597d21171a2000831fab8--compassionate-liskov-fffdb5.netlify.com/

**Comment by David-OConnor** [comment]
Much appreciated! I have this fixed locally (Corrected by using a `r` string with multiple `#`s, so the # in the generated html doesn't break things) Haven't published since I'm fighting through an issue with the latest (unreleased) seed version, that's currently broken for markdown.

I hope to have this fixed, a new seed version released, the site updated soon. Currently the docs (site and readme) have some changes not reflected in the latest release (ie Node instead of El) - let me know if that trips you up.

**Comment by craigmayhew** [comment]
Understood and thanks for the response! I'll close this given you have a better fix!

**Comment by David-OConnor** [comment]
Fixed (The homepage, not underlying md issue)

**Pull request closed without merging**
